name: flutter_adeeinappwebview_internal_annotations
description: Internal annotations used by the generator of flutter_adeeinappwebview plugin
version: 1.1.1
homepage: https://github.com/javadtaghia/flutter_adeeinappwebview

environment:
  sdk: ">=2.15.0 <4.0.0"

dev_dependencies:
  test: ^1.21.6